# src/infrastructure/web/swagger/definitions/auth.yml
tags:
  - name: Authentication
    description: User authentication and authorization endpoints

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Creates a new user account after payment verification
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - stripePaymentIntentId
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                stripePaymentIntentId:
                  type: string
                  example: pi_1234567890
      responses:
        201:
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registration successful. Check your email for login credentials.
                  userId:
                    type: string
                    example: 1234567890-abcdef
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        409:
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User already exists

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      description: Authenticates a user and returns a JWT token
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: audirezk@gmail.com
                password:
                  type: string
                  format: password
                  example: QBdeTGZD#Dq3
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                        format: email
                      role:
                        type: string
                        enum: [ADMIN, INSTRUCTOR, STUDENT]
                  token:
                    type: string
                    description: JWT authentication token
        401:
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid credentials
        403:
          description: Account is inactive
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Account is inactive

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout user
      description: Logs out the current user (client-side token removal)
      security: []
      responses:
        200:
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout successful
